import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemProvede from "@/components/ThemProveder";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "General Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemProvede>{children} </ThemProvede>{" "}
      </body>
    </html>
  );
}
